map_every: 1
keyframe_every: 5
mapping_window_size: 24
tracking_iters: 40
mapping_iters: 60

tracking_factor: 1
mapping_factor: 1
densify_factor: ${eval:'2 if ("${dataset_name}" == "Replica" and "${hydra:runtime.choices.backend@_global_}".startswith("gsplat")) else 1'}