map_every: 1
keyframe_every: 5
mapping_window_size: 6
tracking_iters: 4
mapping_iters: 6
data:
  densification_image_height: ${eval:'340 if "${dataset_name}" == "Replica" else 480'}
  densification_image_width: ${eval:'600 if "${dataset_name}" == "Replica" else 640'}

tracking_factor: 1
mapping_factor: 1
densify_factor: ${eval:'2 if "${dataset_name}" == "Replica" else 1'}