defaults:
 - data@_global_: tum
 - eval@_global_: base
 - tracking: base
 - mapping: base
 - viz: base
 - size@_global_: tiny
 - backend: gsplat
 - _self_

# gaussian
mean_sq_dist_method: 'projective'
gaussian_distribution: 'isotropic'

# train
seed: 0
run_name: '${hydra:runtime.choices.backend}_${hydra:runtime.choices.size@_global_}-${scene_name}-seed${seed}'
workdir: './experiments/${dataset_name}'
output_dir: '${workdir}/${run_name}'
hydra:
  run:
    dir: ${output_dir}
primary_device: 'cuda'
load_checkpoint: False
